#!/bin/bash
# 🚀 GRAMGPT Production Deployment Script
# Deploy to VPS/Cloud Server with single command
# Usage: bash deploy.sh [domain] [server_ip]

set -e  # Exit on error

DOMAIN="${1:-gramgpt.io}"
SERVER_IP="${2:-}"
APP_DIR="/opt/gramgpt"
VENV_DIR="$APP_DIR/venv"
GIT_REPO="https://github.com/kakahka3434-spec/GRAMGPT.git"

echo "🚀 GRAMGPT Production Deployment"
echo "================================"
echo "Domain: $DOMAIN"
echo "App Dir: $APP_DIR"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Helper functions
log_info() { echo -e "${GREEN}✅ $1${NC}"; }
log_warn() { echo -e "${YELLOW}⚠️  $1${NC}"; }
log_error() { echo -e "${RED}❌ $1${NC}"; exit 1; }

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   log_error "This script must be run as root"
fi

log_info "Step 1: Update system packages"
apt-get update -qq
apt-get upgrade -y -qq

log_info "Step 2: Install system dependencies"
apt-get install -y -qq \
    python3.11 \
    python3.11-venv \
    python3.11-dev \
    pip \
    git \
    curl \
    wget \
    nginx \
    certbot \
    python3-certbot-nginx \
    sqlite3 \
    postgresql \
    postgresql-contrib

log_info "Step 3: Clone repository"
if [ -d "$APP_DIR" ]; then
    log_warn "Directory $APP_DIR exists, updating..."
    cd "$APP_DIR"
    git pull origin main
else
    mkdir -p "$APP_DIR"
    git clone "$GIT_REPO" "$APP_DIR"
    cd "$APP_DIR"
fi

log_info "Step 4: Create Python virtual environment"
python3.11 -m venv "$VENV_DIR"
source "$VENV_DIR/bin/activate"

log_info "Step 5: Install Python dependencies"
pip install --upgrade pip setuptools wheel -q
pip install -r requirements.txt -q

log_info "Step 6: Create .env.production"
if [ ! -f "$APP_DIR/.env.production" ]; then
    cat > "$APP_DIR/.env.production" << 'EOF'
# Production Environment Variables
# Generated by deploy.sh - Edit as needed

# Telegram
TELEGRAM_API_ID=12345678
TELEGRAM_API_HASH=abcdef1234567890
TELEGRAM_PHONE=+79990000000

# AI Provider
AI_PROVIDER=openrouter
OPENROUTER_API_KEY=sk-or-...  # Add your key!
OPENAI_API_KEY=

# Database (Production: PostgreSQL)
DATABASE_URL=postgresql://gramgpt:secure_password@localhost/gramgpt

# Server
API_PORT=8000
API_HOST=0.0.0.0
DEBUG=false
LOG_LEVEL=INFO

# Security
SECRET_KEY=generate-random-key-here-32chars
CORS_ORIGINS=["https://gramgpt.io", "https://www.gramgpt.io"]

# Rate limiting
RATE_LIMIT_ENABLED=true
MAX_COMMENTS_PER_HOUR=100
EOF
    log_warn "Created .env.production - EDIT IT with your credentials!"
else
    log_warn "Using existing .env.production"
fi

log_info "Step 7: Setup PostgreSQL database"
sudo -u postgres psql << SQL
CREATE DATABASE gramgpt;
CREATE USER gramgpt WITH PASSWORD 'secure_password';
ALTER ROLE gramgpt SET client_encoding TO 'utf8';
ALTER ROLE gramgpt SET default_transaction_isolation TO 'read committed';
ALTER ROLE gramgpt SET default_transaction_deferrable TO on;
ALTER ROLE gramgpt SET default_transaction_level TO 'read committed';
GRANT ALL PRIVILEGES ON DATABASE gramgpt TO gramgpt;
SQL
log_warn "⚠️ Change password in .env.production!"

log_info "Step 8: Create systemd service"
cat > /etc/systemd/system/gramgpt.service << EOF
[Unit]
Description=GRAMGPT API Service
After=network.target postgresql.service

[Service]
Type=notify
User=gramgpt
WorkingDirectory=$APP_DIR
Environment="PATH=$VENV_DIR/bin"
EnvironmentFile=$APP_DIR/.env.production
ExecStart=$VENV_DIR/bin/python -m uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --workers 4
Restart=on-failure
RestartSec=10s

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable gramgpt
log_info "Service registered: systemctl start gramgpt"

log_info "Step 9: Create gramgpt user"
if ! id "gramgpt" &>/dev/null; then
    useradd -r -s /bin/bash -d "$APP_DIR" gramgpt
    chown -R gramgpt:gramgpt "$APP_DIR"
    log_info "User 'gramgpt' created"
else
    log_warn "User 'gramgpt' already exists"
fi

log_info "Step 10: Configure Nginx"
cat > /etc/nginx/sites-available/gramgpt << EOF
upstream gramgpt_backend {
    server 127.0.0.1:8000;
}

# Redirect HTTP to HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN www.$DOMAIN;
    
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    
    location / {
        return 301 https://\$server_name\$request_uri;
    }
}

# HTTPS server
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name $DOMAIN www.$DOMAIN;

    # SSL certificates (will be created by certbot)
    ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
    
    # SSL configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    
    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    
    # Logging
    access_log /var/log/nginx/gramgpt_access.log;
    error_log /var/log/nginx/gramgpt_error.log;
    
    # Proxy to backend
    location / {
        proxy_pass http://gramgpt_backend;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        
        # Websocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}
EOF

# Enable site
ln -sf /etc/nginx/sites-available/gramgpt /etc/nginx/sites-enabled/gramgpt
rm -f /etc/nginx/sites-enabled/default

# Test nginx config
nginx -t || log_error "Nginx config error"

log_info "Step 11: Setup SSL certificate (Let's Encrypt)"
if command -v certbot &> /dev/null; then
    certbot certonly --webroot -w /var/www/certbot -d "$DOMAIN" -d "www.$DOMAIN" --non-interactive --agree-tos --email admin@$DOMAIN || log_warn "Certbot setup needs manual intervention"
else
    log_warn "Certbot not found - please install SSL manually"
fi

log_info "Step 12: Setup automatic backups"
cat > /usr/local/bin/backup-gramgpt.sh << 'BACKUP_SCRIPT'
#!/bin/bash
BACKUP_DIR="/opt/gramgpt/backups"
DATE=$(date +"%Y-%m-%d_%H-%M-%S")
mkdir -p "$BACKUP_DIR"

# Backup database
pg_dump gramgpt | gzip > "$BACKUP_DIR/gramgpt_$DATE.sql.gz"

# Keep only last 7 days
find "$BACKUP_DIR" -name "gramgpt_*.sql.gz" -mtime +7 -delete

echo "✅ Backup completed: gramgpt_$DATE.sql.gz"
BACKUP_SCRIPT

chmod +x /usr/local/bin/backup-gramgpt.sh

# Add to crontab
(crontab -l 2>/dev/null || echo "") | grep -v "backup-gramgpt" | crontab -
(crontab -l 2>/dev/null || echo ""; echo "0 2 * * * /usr/local/bin/backup-gramgpt.sh") | crontab -

log_info "Step 13: Start services"
systemctl restart nginx
systemctl start gramgpt

# Wait for service to start
sleep 2

if systemctl is-active --quiet gramgpt; then
    log_info "✅ GRAMGPT service is running"
else
    log_error "GRAMGPT service failed to start"
fi

if systemctl is-active --quiet nginx; then
    log_info "✅ Nginx is running"
else
    log_error "Nginx failed to start"
fi

log_info "Step 14: Verify deployment"
sleep 2

HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8000/api/v1/status || echo "000")
if [ "$HTTP_CODE" = "200" ]; then
    log_info "✅ API responding correctly"
else
    log_warn "API returned HTTP $HTTP_CODE"
fi

echo ""
echo "════════════════════════════════════════"
echo "🎉 GRAMGPT Deployment Complete!"
echo "════════════════════════════════════════"
echo ""
echo "📊 Access your application:"
echo "   🌐 https://$DOMAIN"
echo "   🔌 API: https://$DOMAIN/api/v1"
echo ""
echo "📝 Important files:"
echo "   ⚙️  Config: $APP_DIR/.env.production"
echo "   🔍 Logs: journalctl -u gramgpt -f"
echo "   📦 Backups: $APP_DIR/backups/"
echo ""
echo "🚀 Next steps:"
echo "   1. Edit $APP_DIR/.env.production with real credentials"
echo "   2. Setup your Telegram Bot with @BotFather"
echo "   3. Update DNS to point to this server"
echo "   4. Renew SSL: certbot renew --dry-run"
echo ""
echo "💬 Commands:"
echo "   systemctl status gramgpt              # Service status"
echo "   systemctl restart gramgpt             # Restart service"
echo "   journalctl -u gramgpt -f              # Live logs"
echo "   /usr/local/bin/backup-gramgpt.sh      # Manual backup"
echo ""
echo "════════════════════════════════════════"
